### PR TITLE
Fix print "undefined"

### PR DESCRIPTION
**Pull request by Skriptach**
Before
image

After
image

### CODE REVIEW

**Comment by RasPhilCo** [comment]
Interesting! What shell are you using in the screen shot?

**Comment by Skriptach** [comment]
Node from Electron

**Comment by RasPhilCo** [comment]
@Skriptach I merge in some master changes that were blocking this. Let me know when you get a chance to sign the CLA and then I can merge this.

**Comment by Skriptach** [comment]
> sign the CLA

Done

**Pull request merged**
