### PR TITLE
Update lodash.template

### PR DESCRIPTION
**Pull request by mattwiller**
I received a security alert for the lodash.template dependency,
indicating that it was potentially vulnerable to prototype
pollution.  Updating to v4.5.0 or above was recommended as the
fix.

### CODE REVIEW

**Comment by mattwiller** [comment]
Any chance of getting this merged?  I'd like to get GitHub to stop warning me about this issue in my CLI project :)

**Comment by RasPhilCo** [comment]
Looks like dependabot got this, but thanks for the ping/reminder!

**Comment by mattwiller** [comment]
@RasPhilCo Ah, great — thanks for pushing out the new version!

**Comment by dmarvasti** [comment]
@mattwiller @RasPhilCo - I'm not seeing that lodash.template 4.5.0 actually made it to the latest version of oclif/plugin-help.

**Comment by RasPhilCo** [comment]
https://github.com/oclif/plugin-help/blob/master/yarn.lock#L1821-L1822

**Pull request closed without merging**
